Добавляет оптимизацию картинок
htmlacademy-adaptive/2379901-cat-energy-1 pull request #6
Opened 2024-07-09 08:07 UTC by IlmeinenLiian

2024-07-10 06:29 UTC, andreysgra requested changes

2024-07-10 06:29 UTC, andreysgra commented on source/catalog.html
> +          <source media="(min-width: 1200px)" srcset="img/logo-desctop.svg" width="59" heigth="70">
Если у вас переход на десктопную версию начинается с 1300px, то и логотип нужно менять на этом же разрешении.

2024-07-10 06:29 UTC, andreysgra commented on source/form.html
> +          <source media="(min-width: 1200px)" srcset="img/logo-desctop.svg" width="59" heigth="70">
Здесь тоже самое.

2024-07-10 06:29 UTC, andreysgra commented on source/index.html
> +          <source media="(min-width: 1200px)" srcset="img/logo-desctop.svg" width="59" heigth="70">
Здесь тоже самое.

2024-07-10 06:29 UTC, andreysgra commented on source/index.html
> +          <source media="(min-width: 1200px)" srcset="img/index-can-desctop-x1.png 1x, img/index-can-desctop-x2.png 2x" width="552" height="499">
Здесь тоже самое.

2024-07-10 06:29 UTC, andreysgra commented on source/sass/blocks/form-feedback.scss
> +    width: 1000%;
Такой приём для `.form-feedback__comments-title` работает некорректно, появляется горизонтальная полоса прокрутки. Посмотрите пример реализации зелёной полосы [здесь](https://bnvnik.github.io/2165163-cat-energy-31/catalog.html).

2024-07-10 06:29 UTC, andreysgra commented on source/sass/blocks/page-header.scss
> +      background-image: url("../img/index-background-desktop-x2.jpg");
Здесь не вполне удачная реализация. Чем больше разрешение экрана, тем больше видна разница между фоновым цветом и изображением:

![image](https://github.com/htmlacademy-adaptive/2379901-cat-energy-1/assets/17790771/f03f33d9-1f70-4408-8845-972b26f2f6a7)

`::before` здесь нет необходимости использовать. Пример реализации можно посмотреть [здесь](https://codepen.io/angra/pen/zYYVqRP).

2024-07-13 20:10 UTC, IlmeinenLiian commented
Если фоновое изображение делаю как в примере, то получается вот так

2024-07-16 08:33 UTC, andreysgra requested changes
Что касается фонового изображения кота в шапке сайта объедините слои в фигме и извлеките как одно изображение:

![image](https://github.com/user-attachments/assets/164efba9-20ea-4884-9d8d-c745371fec57)

2024-07-16 08:33 UTC, andreysgra commented on source/sass/blocks/purpose.scss
> +width: 460px;
В десктопной версии ширина `.purpose__description` явно меньше этого значения, иначе `..purpose__item` выходит за пределы родительского элемента и появляется полоса прокрутки:

![image](https://github.com/user-attachments/assets/4ad45854-fb67-4847-ad5d-776250947694)

2024-07-17 18:33 UTC, merged